// <auto-generated />
using LazyPinger.Base.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LazyPinger.Base.Migrations
{
    [DbContext(typeof(LazyPingerDbContext))]
    [Migration("20250829181010_UpdatedDeviceGroups")]
    partial class UpdatedDeviceGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("LazyPinger.Base.Models.Devices.DevicePing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevicesGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsIpBased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubnetRangeMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubnetRangeMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserSelectionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DevicesGroupID");

                    b.HasIndex("UserSelectionID");

                    b.ToTable("DevicePings");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.Devices.DevicesGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserSelectionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserSelectionID");

                    b.ToTable("DevicesGroups");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.User.UserPreference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.User.UserSelection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRestart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRestartTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRun")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FastPing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FastnessLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPreferenceID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserPreferenceID")
                        .IsUnique();

                    b.ToTable("UserSelections");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.Devices.DevicePing", b =>
                {
                    b.HasOne("LazyPinger.Base.Models.Devices.DevicesGroup", "DevicesGroup")
                        .WithMany("DevicePings")
                        .HasForeignKey("DevicesGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LazyPinger.Base.Models.User.UserSelection", "UserSelection")
                        .WithMany("DevicesPing")
                        .HasForeignKey("UserSelectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevicesGroup");

                    b.Navigation("UserSelection");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.Devices.DevicesGroup", b =>
                {
                    b.HasOne("LazyPinger.Base.Models.User.UserSelection", "UserSelection")
                        .WithMany()
                        .HasForeignKey("UserSelectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSelection");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.User.UserSelection", b =>
                {
                    b.HasOne("LazyPinger.Base.Models.User.UserPreference", "UserPreference")
                        .WithOne("UserSelection")
                        .HasForeignKey("LazyPinger.Base.Models.User.UserSelection", "UserPreferenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreference");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.Devices.DevicesGroup", b =>
                {
                    b.Navigation("DevicePings");
                });

            modelBuilder.Entity("LazyPinger.Base.Models.User.UserPreference", b =>
                {
                    b.Navigation("UserSelection")
                        .IsRequired();
                });

            modelBuilder.Entity("LazyPinger.Base.Models.User.UserSelection", b =>
                {
                    b.Navigation("DevicesPing");
                });
#pragma warning restore 612, 618
        }
    }
}
