name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore /workspaces/LazyPinger/LazyPinger.Tests
    - name: Build
      run: dotnet /workspaces/LazyPinger/LazyPinger.Tests --no-restore
    - name: Test
      run: dotnet test /workspaces/LazyPinger/LazyPinger.Tests --no-build --verbosity normal
