name: .NET CI

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  
  build:
      runs-on: ubuntu-latest

    
      steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install .NET MAUI Workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore LazyPinger.sln

      
      - name: Build
        run: dotnet build LazyPinger.sln --no-restore

      - name: Test
        run: dotnet test LazyPinger.sln --no-build --verbosity normal
